---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
network.host: "0.0.0.0"
server.shutdownTimeout: "5s"
elasticsearch.hosts: [ "http://es01:9200" ]

# bin/elasticsearch-reset-password -u kibana_system --auto
elasticsearch.username: "kibana_system"
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}
#
monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

